version: "2"
linters:
  default: standard
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
output:
  formats:
    text:
      path: ./golangci-report.txt
      print-linter-name: false
      print-issued-lines: false
      colors: false
